"""
run_multi_agent_review_v0_1.py  (05_SRC/analysis/)

AOSL Multi-Agent Review v0.1
-----------------------------
Five-agent pipeline that scores, critiques, repairs, re-scores, and
reports on a single AI output.

Agents
------
1. Scoring Agent   — AOSL constraint scoring on original output (score_row_real_judge)
2. Critic Agent    — Free-text structural critique via judge model
3. Repair Agent    — Revised output generated by the same judge model
4. Re-score Agent  — AOSL constraint scoring on repaired output
5. Report Agent    — Markdown + CSV report written to output folder

Usage
-----
Dry run (prints plan, no API calls):
    py 05_SRC\\analysis\\run_multi_agent_review_v0_1.py --dry-run

Live run with built-in demo input:
    py 05_SRC\\analysis\\run_multi_agent_review_v0_1.py

Options:
    --judge-model   OpenRouter model ID  (default: deepseek/deepseek-chat)
    --max-tokens    Max tokens per call  (default: 500)
    --timeout       Seconds per call     (default: 90)
    --prompt        Override demo prompt text
    --output        Override demo output text
    --dry-run       Print plan only, no API calls

Output folder: 06_OUTPUTS/multi_agent_review/v0_1/
"""

import argparse
import csv
import json
import sys
import textwrap
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# sys.path setup
# ---------------------------------------------------------------------------
_REPO_ROOT = Path(__file__).resolve().parents[2]
_SRC_ROOT  = Path(__file__).resolve().parents[1]

for _p in (str(_REPO_ROOT), str(_SRC_ROOT)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from scoring.fast_batch_scorer import (
    score_row_real_judge,
    DEFAULT_JUDGE_MODEL,
    CONSTRAINT_CODES,
)
from api.openrouter_client import generate_response

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
OUTPUT_DIR = _REPO_ROOT / "06_OUTPUTS" / "multi_agent_review" / "v0_1"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

CONSTRAINT_NAMES = {
    "c1":  "Factual Grounding",
    "c2":  "Logical Coherence",
    "c3":  "Causal Integrity",
    "c4":  "Epistemic Calibration",
    "c5":  "Scope Discipline",
    "c6":  "Safety Integrity",
    "c7":  "Uncertainty Acknowledgment",
    "c8":  "Quantitative Accuracy",
    "c9":  "Evidence Traceability",
    "c10": "Constraint Interaction Consistency",
}

DEMO_PROMPT = (
    "Our app engagement dropped 20% last week. "
    "We also added a new onboarding screen last week. "
    "What caused the drop?"
)
DEMO_OUTPUT = (
    "The onboarding screen caused the engagement drop. "
    "Adding new screens always disrupts user flow and reduces engagement. "
    "You should remove it immediately to restore your metrics."
)

# ---------------------------------------------------------------------------
# Agent helpers
# ---------------------------------------------------------------------------

def _weakest_constraints(score_result: dict, n: int = 3) -> list[tuple[str, float]]:
    """Return up to n constraints with the lowest (worst) scores."""
    pairs = []
    for code in CONSTRAINT_CODES:
        val = score_result.get(code)
        if val is not None:
            pairs.append((code, float(val)))
    pairs.sort(key=lambda x: x[1])
    return pairs[:n]


def _format_score_table(score_result: dict) -> str:
    lines = ["| Code | Constraint | Score |", "|------|------------|-------|"]
    for code in CONSTRAINT_CODES:
        val = score_result.get(code)
        if val is not None:
            label = "PASS" if float(val) == 1.0 else ("PARTIAL" if float(val) == 0.5 else "FAIL")
            lines.append(f"| {code.upper()} | {CONSTRAINT_NAMES.get(code, code)} | {float(val):.1f} ({label}) |")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Agent 1: Scoring Agent
# ---------------------------------------------------------------------------

def agent_score(prompt_text: str, output_text: str, judge_model: str,
                max_tokens: int, timeout: int) -> dict:
    """Score original output with AOSL constraints."""
    print("[Agent 1 / Scoring] Scoring original output...")
    row = {
        "prompt_id":   "mar_input",
        "prompt_text": prompt_text,
        "output_text": output_text,
    }
    result = score_row_real_judge(
        row,
        judge_model=judge_model,
        timeout=float(timeout),
        max_tokens=max_tokens,
    )
    d = result.get("divergence", "?")
    tier = result.get("stability_tier", "?")
    print(f"[Agent 1 / Scoring] Done. D={d:.4f}, tier={tier}" if isinstance(d, float) else f"[Agent 1 / Scoring] Done. D={d}, tier={tier}")
    return result


# ---------------------------------------------------------------------------
# Agent 2: Critic Agent
# ---------------------------------------------------------------------------

_CRITIC_PROMPT_TEMPLATE = """\
You are a structural critic reviewing an AI output for logical and epistemic weaknesses.
Focus only on structural problems — do not fact-check external claims.

Original prompt:
{prompt_text}

AI output to review:
{output_text}

Weakest structural constraints already detected (AOSL scores, lower = worse):
{weakest_list}

Write a brief structural critique covering:
1. What specific structural problems does this output have?
2. Which patterns are present: causal leaps, overconfidence, missing uncertainty, \
weak evidence, scope drift, safety risks?
3. What would a structurally sound version of this answer need to include or change?

Be specific and direct. 3-5 sentences maximum.
"""

def agent_critique(prompt_text: str, output_text: str, score_result: dict,
                   judge_model: str, max_tokens: int, timeout: int) -> str:
    """Generate a free-text structural critique of the output."""
    print("[Agent 2 / Critic] Generating structural critique...")
    weakest = _weakest_constraints(score_result, n=3)
    weakest_list = "\n".join(
        f"  - {CONSTRAINT_NAMES.get(c, c)} ({c}): {v:.1f}" for c, v in weakest
    )
    critic_prompt = _CRITIC_PROMPT_TEMPLATE.format(
        prompt_text=prompt_text,
        output_text=output_text,
        weakest_list=weakest_list,
    )
    critique = generate_response(
        model=judge_model,
        prompt=critic_prompt,
        temperature=0.3,
        max_tokens=max_tokens,
    )
    print(f"[Agent 2 / Critic] Done. Critique length: {len(critique)} chars.")
    return critique


# ---------------------------------------------------------------------------
# Agent 3: Repair Agent
# ---------------------------------------------------------------------------

_REPAIR_PROMPT_TEMPLATE = """\
You are a careful AI assistant. Rewrite the following AI output to fix its structural weaknesses.

Original prompt:
{prompt_text}

Original output (with structural problems):
{output_text}

Structural critique:
{critique}

Weakest constraints to fix (lower score = worse):
{weakest_list}

Instructions:
- Fix the identified structural problems.
- Do not add information that was not in the original output.
- Keep the answer concise and on-topic.
- Acknowledge uncertainty where appropriate.
- Avoid causal claims that are not supported.

Write only the repaired output. No preamble.
"""

def agent_repair(prompt_text: str, output_text: str, critique: str,
                 score_result: dict, judge_model: str,
                 max_tokens: int, timeout: int) -> str:
    """Generate a structurally repaired version of the output."""
    print("[Agent 3 / Repair] Generating repaired output...")
    weakest = _weakest_constraints(score_result, n=3)
    weakest_list = "\n".join(
        f"  - {CONSTRAINT_NAMES.get(c, c)} ({c}): {v:.1f}" for c, v in weakest
    )
    repair_prompt = _REPAIR_PROMPT_TEMPLATE.format(
        prompt_text=prompt_text,
        output_text=output_text,
        critique=critique,
        weakest_list=weakest_list,
    )
    repaired = generate_response(
        model=judge_model,
        prompt=repair_prompt,
        temperature=0.3,
        max_tokens=max_tokens,
    )
    print(f"[Agent 3 / Repair] Done. Repaired output length: {len(repaired)} chars.")
    return repaired


# ---------------------------------------------------------------------------
# Agent 4: Re-score Agent
# ---------------------------------------------------------------------------

def agent_rescore(prompt_text: str, repaired_output: str, judge_model: str,
                  max_tokens: int, timeout: int) -> dict:
    """Score the repaired output with AOSL constraints."""
    print("[Agent 4 / Re-score] Scoring repaired output...")
    row = {
        "prompt_id":   "mar_repaired",
        "prompt_text": prompt_text,
        "output_text": repaired_output,
    }
    result = score_row_real_judge(
        row,
        judge_model=judge_model,
        timeout=float(timeout),
        max_tokens=max_tokens,
    )
    d = result.get("divergence", "?")
    tier = result.get("stability_tier", "?")
    print(f"[Agent 4 / Re-score] Done. D={d:.4f}, tier={tier}" if isinstance(d, float) else f"[Agent 4 / Re-score] Done. D={d}, tier={tier}")
    return result


# ---------------------------------------------------------------------------
# Agent 5: Report Agent
# ---------------------------------------------------------------------------

def agent_report(
    prompt_text:     str,
    original_output: str,
    repaired_output: str,
    critique:        str,
    original_score:  dict,
    repaired_score:  dict,
    judge_model:     str,
    run_ts:          str,
) -> tuple[Path, Path]:
    """Write Markdown and CSV reports. Returns (md_path, csv_path)."""
    print("[Agent 5 / Report] Writing reports...")

    d_orig = float(original_score.get("divergence", 0.0))
    d_rep  = float(repaired_score.get("divergence", 0.0))
    d_delta = d_orig - d_rep
    tier_orig = original_score.get("stability_tier", "—")
    tier_rep  = repaired_score.get("stability_tier", "—")

    # ---- Markdown ----
    md_lines = [
        "# AOSL Multi-Agent Review Report",
        "",
        f"**Run timestamp:** {run_ts}  ",
        f"**Judge model:** `{judge_model}`  ",
        f"**Script:** `run_multi_agent_review_v0_1.py`",
        "",
        "---",
        "",
        "## Input",
        "",
        "**Prompt:**",
        "",
        f"> {prompt_text}",
        "",
        "**Original output:**",
        "",
        f"> {original_output}",
        "",
        "---",
        "",
        "## Agent 1 — Original Score",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Divergence (D) | {d_orig:.4f} |",
        f"| Stability tier | {tier_orig} |",
        "",
        _format_score_table(original_score),
        "",
        "---",
        "",
        "## Agent 2 — Structural Critique",
        "",
        critique,
        "",
        "---",
        "",
        "## Agent 3 — Repaired Output",
        "",
        f"> {repaired_output}",
        "",
        "---",
        "",
        "## Agent 4 — Re-score",
        "",
        f"| Metric | Original | Repaired | Delta |",
        f"|--------|----------|----------|-------|",
        f"| Divergence (D) | {d_orig:.4f} | {d_rep:.4f} | {'-' if d_delta >= 0 else '+'}{abs(d_delta):.4f} |",
        f"| Stability tier | {tier_orig} | {tier_rep} | — |",
        "",
        _format_score_table(repaired_score),
        "",
        "---",
        "",
        "## Agent 5 — Summary",
        "",
    ]

    if d_delta > 0.01:
        md_lines.append(f"Repair **improved** structural quality. D dropped {d_delta:.4f} ({d_orig:.4f} → {d_rep:.4f}).")
    elif d_delta < -0.01:
        md_lines.append(f"Repair **did not improve** structural quality. D increased {abs(d_delta):.4f} ({d_orig:.4f} → {d_rep:.4f}).")
    else:
        md_lines.append(f"Repair produced **minimal change** in D ({d_orig:.4f} → {d_rep:.4f}).")

    md_lines += [
        "",
        "Per-constraint changes (original → repaired):",
        "",
        "| Code | Constraint | Original | Repaired | Change |",
        "|------|------------|----------|----------|--------|",
    ]
    for code in CONSTRAINT_CODES:
        v_orig = original_score.get(code)
        v_rep  = repaired_score.get(code)
        if v_orig is not None and v_rep is not None:
            delta = float(v_rep) - float(v_orig)
            arrow = "+" if delta > 0 else ("-" if delta < 0 else "=")
            md_lines.append(
                f"| {code.upper()} | {CONSTRAINT_NAMES.get(code, code)} "
                f"| {float(v_orig):.1f} | {float(v_rep):.1f} | {arrow}{abs(delta):.1f} |"
            )

    md_lines += [
        "",
        "---",
        "",
        "```",
        "Version : v0.1",
        f"Created : {run_ts}",
        "Status  : research output — not for production use",
        "```",
    ]

    md_path = OUTPUT_DIR / f"multi_agent_review_report_{run_ts}.md"
    md_path.write_text("\n".join(md_lines), encoding="utf-8")
    print(f"[Agent 5 / Report] Markdown written: {md_path.name}")

    # ---- CSV ----
    csv_path = OUTPUT_DIR / f"multi_agent_review_summary_{run_ts}.csv"
    fieldnames = [
        "run_ts", "judge_model",
        "d_original", "tier_original",
        "d_repaired", "tier_repaired",
        "d_delta",
    ] + [f"{c}_original" for c in CONSTRAINT_CODES] + [f"{c}_repaired" for c in CONSTRAINT_CODES]

    row = {
        "run_ts":        run_ts,
        "judge_model":   judge_model,
        "d_original":    round(d_orig, 6),
        "tier_original": tier_orig,
        "d_repaired":    round(d_rep, 6),
        "tier_repaired": tier_rep,
        "d_delta":       round(d_delta, 6),
    }
    for code in CONSTRAINT_CODES:
        row[f"{code}_original"] = original_score.get(code, "")
        row[f"{code}_repaired"] = repaired_score.get(code, "")

    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerow(row)
    print(f"[Agent 5 / Report] CSV written:      {csv_path.name}")

    return md_path, csv_path


# ---------------------------------------------------------------------------
# Dry-run plan printer
# ---------------------------------------------------------------------------

def print_dry_run(prompt_text: str, output_text: str, judge_model: str,
                  max_tokens: int, timeout: int) -> None:
    print()
    print("=" * 60)
    print("AOSL Multi-Agent Review v0.1 — DRY RUN (no API calls)")
    print("=" * 60)
    print()
    print("Pipeline:")
    print("  Agent 1  Scoring Agent    score_row_real_judge() on original output")
    print("  Agent 2  Critic Agent     generate_response() → structured critique")
    print("  Agent 3  Repair Agent     generate_response() → repaired output")
    print("  Agent 4  Re-score Agent   score_row_real_judge() on repaired output")
    print("  Agent 5  Report Agent     write .md + .csv to output folder")
    print()
    print("Settings:")
    print(f"  judge_model : {judge_model}")
    print(f"  max_tokens  : {max_tokens}")
    print(f"  timeout     : {timeout}s")
    print()
    print("Input prompt:")
    for line in textwrap.wrap(prompt_text, width=72):
        print(f"  {line}")
    print()
    print("Input output (original):")
    for line in textwrap.wrap(output_text, width=72):
        print(f"  {line}")
    print()
    print("Output folder:")
    print(f"  {OUTPUT_DIR}")
    print()
    print("Run without --dry-run to execute all five agents.")
    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="AOSL Multi-Agent Review v0.1 — score, critique, repair, re-score, report."
    )
    parser.add_argument("--judge-model", default=DEFAULT_JUDGE_MODEL,
                        help=f"OpenRouter model ID (default: {DEFAULT_JUDGE_MODEL})")
    parser.add_argument("--max-tokens", type=int, default=500,
                        help="Max tokens per API call (default: 500)")
    parser.add_argument("--timeout", type=int, default=90,
                        help="Timeout in seconds per API call (default: 90)")
    parser.add_argument("--prompt", default=None,
                        help="Override demo prompt text")
    parser.add_argument("--output", default=None,
                        help="Override demo output text")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print plan only — no API calls")
    args = parser.parse_args()

    prompt_text  = args.prompt or DEMO_PROMPT
    output_text  = args.output or DEMO_OUTPUT
    judge_model  = args.judge_model
    max_tokens   = args.max_tokens
    timeout      = args.timeout

    if args.dry_run:
        print_dry_run(prompt_text, output_text, judge_model, max_tokens, timeout)
        return

    run_ts = datetime.now().strftime("%Y%m%d_%H%M%S")

    print()
    print("=" * 60)
    print("AOSL Multi-Agent Review v0.1")
    print("=" * 60)
    print(f"Judge model : {judge_model}")
    print(f"Max tokens  : {max_tokens}")
    print(f"Timeout     : {timeout}s")
    print(f"Run ID      : {run_ts}")
    print()

    # Agent 1: Score original
    original_score = agent_score(prompt_text, output_text, judge_model, max_tokens, timeout)
    if original_score.get("scorer_error"):
        print(f"[ERROR] Agent 1 failed: {original_score['scorer_error']}")
        sys.exit(1)
    print()

    # Agent 2: Critique
    critique = agent_critique(prompt_text, output_text, original_score,
                              judge_model, max_tokens, timeout)
    print()

    # Agent 3: Repair
    repaired_output = agent_repair(prompt_text, output_text, critique, original_score,
                                   judge_model, max_tokens, timeout)
    print()

    # Agent 4: Re-score
    repaired_score = agent_rescore(prompt_text, repaired_output, judge_model, max_tokens, timeout)
    if repaired_score.get("scorer_error"):
        print(f"[ERROR] Agent 4 failed: {repaired_score['scorer_error']}")
        sys.exit(1)
    print()

    # Agent 5: Report
    md_path, csv_path = agent_report(
        prompt_text=prompt_text,
        original_output=output_text,
        repaired_output=repaired_output,
        critique=critique,
        original_score=original_score,
        repaired_score=repaired_score,
        judge_model=judge_model,
        run_ts=run_ts,
    )
    print()

    d_orig  = float(original_score.get("divergence", 0.0))
    d_rep   = float(repaired_score.get("divergence", 0.0))
    d_delta = d_orig - d_rep

    print("=" * 60)
    print("Run complete.")
    print(f"  D original  : {d_orig:.4f}  ({original_score.get('stability_tier', '—')})")
    print(f"  D repaired  : {d_rep:.4f}  ({repaired_score.get('stability_tier', '—')})")
    print(f"  Delta       : {'-' if d_delta >= 0 else '+'}{abs(d_delta):.4f}")
    print(f"  Report      : {md_path}")
    print(f"  CSV         : {csv_path}")
    print("=" * 60)
    print()


if __name__ == "__main__":
    main()
